# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be50e857597c20ecefea51eb7720a4cbac4a638a3fc0be33d535ff9a995ae0829bf46ad6b78babb18e0d73a6d3a93ffef9a4d4e50aedddff0abf2ff2324345bf

test:
  secret_key_base: 5b2bbc0f7509e9b9a8dd4b339cd9aecb22fc320de2a4c0098827d67600aa3093e05c209c129e8b76ead6387d10f22d08b61b98c00503de75de18024343a4fa0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
